/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application;

import static Application.frmLogin.USER;

import BusinessLayer.MailDTO;
import BusinessLayer.UserDTO;
import Model.MailModel;
import Model.Request;
import Model.StringUtils;
import Model.User;
import com.google.gson.Gson;
import java.io.DataInput;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vothu
 */
public class frmSendmail extends javax.swing.JFrame {

  /**
   * Creates new form frmSendmail
   */
  public Socket socket;
  public String username;
  public frmSendmail() {
    initComponents();
  }
  public frmSendmail(String username,Socket socket) {
    initComponents();
    this.socket = socket;
    this.username = username;
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    txtReciver = new javax.swing.JTextField();
    btnSend = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    txtSubject = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtMessage = new javax.swing.JTextArea();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtReciver.setText("ductai");

    btnSend.setText("Send");
    btnSend.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnSendActionPerformed(evt);
        }
      }
    );

    jLabel2.setText("To:");

    jLabel3.setText("Subject");

    jLabel4.setText("Message");

    txtSubject.setText("hello");
    txtSubject.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          txtSubjectActionPerformed(evt);
        }
      }
    );

    txtMessage.setColumns(20);
    txtMessage.setRows(5);
    txtMessage.setText("I am Nhon\n");
    jScrollPane1.setViewportView(txtMessage);

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jLabel5.setText("Send mail");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING
                    )
                    .addGroup(
                      javax.swing.GroupLayout.Alignment.TRAILING,
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.TRAILING,
                              false
                            )
                            .addGroup(
                              layout
                                .createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(
                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                                .addComponent(
                                  txtReciver,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  223,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                            .addGroup(
                              layout
                                .createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(
                                  txtSubject,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  223,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(
                              jScrollPane1,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                    .addComponent(
                      btnSend,
                      javax.swing.GroupLayout.Alignment.TRAILING
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabel5)
                )
            )
            .addContainerGap(83, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(16, Short.MAX_VALUE)
            .addComponent(
              jLabel5,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              38,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(
                  txtReciver,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  txtSubject,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel3)
            )
            .addGap(13, 13, 13)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(
                  jScrollPane1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addComponent(btnSend)
            .addGap(36, 36, 36)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {}                                                                                       

  private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
    try{
        if(socket==null){
            JOptionPane.showMessageDialog(rootPane, "Khong the gui mail");
            return;
        }
        DataInputStream in = new DataInputStream(socket.getInputStream());
        DataOutputStream out = new DataOutputStream(socket.getOutputStream());
        Date today = new Date(System.currentTimeMillis());
        MailModel mail = new MailModel(txtSubject.getText(),txtMessage.getText(),today,username,txtReciver.getText());
        Request r = new Request(StringUtils.SENDMAIL, mail);
        Gson gson = new Gson();
        String s = gson.toJson(r);
        out.writeUTF(s);
        s = in.readUTF();
        JOptionPane.showMessageDialog(rootPane, s);
        if(s.equals(StringUtils.SENDED))
            this.dispose();
    }catch(Exception e){}
  }//GEN-LAST:event_btnSendActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(frmSendmail.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(frmSendmail.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(frmSendmail.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(frmSendmail.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new frmSendmail().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSend;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtMessage;
  private javax.swing.JTextField txtReciver;
  private javax.swing.JTextField txtSubject;
  // End of variables declaration//GEN-END:variables
}
