/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import BusinessLayer.MailDTO;
import Model.Mail;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmMain extends javax.swing.JFrame {

  /**
   * Creates new form frmMain
   */
  public frmMain() {
    initComponents();
    FillSummaryList();
  }

  public void FillSummaryList() {
    DefaultListModel dm = new DefaultListModel();

    MailDTO mail = new MailDTO();
    ArrayList<Mail> list = mail.Getlist();
    for (int i = 0; i < list.size(); i++) {
      dm.addElement(list.get(i).getSummary());
    }
    lstMail.setModel(dm);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    txtDomain = new javax.swing.JTextField();
    btnEnter = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    lstMail = new javax.swing.JList<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    lstDetail = new javax.swing.JList<>();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    mRegister = new javax.swing.JMenuItem();
    mClose = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("IP/Domain");

    btnEnter.setText("Enter");
    btnEnter.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnEnterActionPerformed(evt);
        }
      }
    );

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jLabel5.setText("Welcome to mail fake");

    lstMail.setModel(
      new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

        public int getSize() {
          return strings.length;
        }

        public String getElementAt(int i) {
          return strings[i];
        }
      }
    );
    lstMail.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          lstMailMouseClicked(evt);
        }
      }
    );
    jScrollPane2.setViewportView(lstMail);

    jScrollPane1.setViewportView(lstDetail);

    jLabel2.setText("Detail");

    jLabel3.setText("Summary");

    jMenu1.setText("System");

    mRegister.setText("Send mail");
    mRegister.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          mRegisterActionPerformed(evt);
        }
      }
    );
    jMenu1.add(mRegister);

    mClose.setText("Close");
    mClose.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          mCloseActionPerformed(evt);
        }
      }
    );
    jMenu1.add(mClose);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(txtDomain)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel3)
                        .addComponent(
                          jScrollPane2,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          320,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      26,
                      Short.MAX_VALUE
                    )
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          jScrollPane1,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          477,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(jLabel2)
                    )
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEnter)
            .addContainerGap()
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(313, 313, 313)
            .addComponent(jLabel5)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addComponent(
              jLabel5,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              38,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(
                  txtDomain,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(btnEnter)
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jScrollPane1,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  294,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jScrollPane2,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  294,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(36, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void mCloseActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_mCloseActionPerformed
    // TODO add your handling code here:
    dispose();
  } //GEN-LAST:event_mCloseActionPerformed

  private void mRegisterActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_mRegisterActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_mRegisterActionPerformed

  private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnEnterActionPerformed
    // TODO add your handling code here:
    String domain = txtDomain.getText();
    MailDTO mail = new MailDTO();
    if (mail.checkDomainIp(domain)) {
      JOptionPane.showMessageDialog(rootPane, "Sucessfully");
    } else {
      JOptionPane.showMessageDialog(
        rootPane,
        "Your domain/ip is invalied!!! Enter again"
      );
    }
  } //GEN-LAST:event_btnEnterActionPerformed

  // To do: can't get detail mail by click on list mail
  // Solution: use
  private void lstMailMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_lstMailMouseClicked
    MailDTO mail = new MailDTO();
    DefaultListModel dm = new DefaultListModel();
    Mail m = new Mail();
    m = mail.GetMailById(lstMail.getSelectedIndex() + 1);
    dm.addElement(m.getAll());
    lstDetail.setModel(dm);
  } //GEN-LAST:event_lstMailMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(frmMain.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(frmMain.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(frmMain.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(frmMain.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new frmMain().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEnter;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JList<String> lstDetail;
  private javax.swing.JList<String> lstMail;
  private javax.swing.JMenuItem mClose;
  private javax.swing.JMenuItem mRegister;
  private javax.swing.JTextField txtDomain;
  // End of variables declaration//GEN-END:variables
}
